GET http://localhost:3000/api/proyectos

###

POST http://localhost:3000/api/proyectos
Content-Type: application/json

{
    "titulo": "Proyecto de prueba"
}

###

PUT http://localhost:3000/api/proyectos

###

DELETE http://localhost:3000/api/proyectos