GET http://localhost:3000/api/proyectos
access-token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c3VhcmlvIjoiSmF2aWVyIiwiY3JlYXRlQXQiOjE2MDAxMTcwNDIsImV4cGlyZWRBdCI6MTYwMDExNzM0Mn0.TfEtzYzWRXhw7zuIQdU0FIwLiRsMcA_sj8RyoH6pfYg

###

POST http://localhost:3000/api/proyectos
Content-Type: application/json

{
    "titulo": "Proyecto de prueba2",
    "descripcion": "Esta es la descripcion",
    "url": "http://www.google.es",
    "cliente": "Google",
    "url_cliente": "http://www.google.com/quien-somos"
}

###

PUT http://localhost:3000/api/proyectos/5f565860fcfab438a8c2a635
Content-Type: application/json

{
    "titulo": "Proyecto editado V2",
    "descripcion": "Esta es la descripcion",
    "url": "http://www.google.es",
    "cliente": "Google",
    "url_cliente": "http://www.google.com/quien-somos"
}

###

DELETE http://localhost:3000/api/proyectos/5f565c03ae1a373658ab7487

###

GET http://localhost:3000/api/token